
["General Configs"]
	#If true: Allow Conjure Water (etc.) to place water in the Nether (etc.) when magnitude has been increased.
	"Can conjure fluid ignore vaporize?" = true
	"If true: The Mark Component supports PlayerCharms" = true
	"If true: The Alternative Recall Component supports PlayerCharms" = true
	"If true: The range of the Alternative Recall Component is unlimited when the range attribute is at maximum level? " = true
	"This number indicates the factor by which the cooldown is increased when casting the spell via the Bracelet of Spell Storing - Cooldown:" = 10

["Upgrade Configs"]

	["Upgrade Configs"."Damage Resistance upgrade"]
		#Range: 0 ~ 33
		"By what percentage is the damage reduced by the damage resistance upgrade (in %):" = 20

	["Upgrade Configs"."Fire Resistance upgrade"]
		#Range: 0 ~ 200
		"How much mana does the fire resistance upgrade consume for one tick of fire damage?" = 20

	["Upgrade Configs"."Fly upgrade"]
		#The airspeed is calculated with this value v. (Airspeed = v * upgrade level / 100). The default Creaktiv flight speed is 0.5
		#Range: 0 ~ 10
		"Flight Speed per Level:" = 2
		"Can the wearer sprint in the air with the Fly Upgrade?" = true

	["Upgrade Configs"."Meteor Jump upgrade"]
		#Range: 1 ~ 5
		"Strength of the Impact:" = 3

	["Upgrade Configs"."Projectile Reflection"]
		#Range: 20 ~ 4000
		"How many ticks it takes to regenerate a Charge:" = 400

	["Upgrade Configs"."Saturation upgrade"]
		#Range: 0 ~ 200
		"Mana cost per nutrition:" = 15

	["Upgrade Configs"."Waterbreathing upgrade"]
		#Range: 0 ~ 100
		"Mana cost per oxigen bubble:" = 20

